from django.urls import path

from . import views

app_name = "applications"

urlpatterns = [
    path(
        "applications/api/node-filter/operators/",
        views.NodeFilterOperatorsView.as_view(),
        name="node_filter_operators",
    ),
    path(
        "applications/",
        views.ApplicationListFormView.as_view(),
        name="application_list",
    ),
    path(
        "applications/new/",
        views.ApplicationEditorStartFormView.as_view(),
        name="new_application",
    ),
    path(
        "applications/deletes/",
        views.MultiApplicationDeletionFormView.as_view(),
        name="delete_applications",
    ),
    path(
        "applications/api/<resource_id>/editor/one-to-one-section/<fk_column_name>/",
        views.ApplicationOneToOneFieldPopupSectionView.as_view(),
        name="application_one_to_one_field_popup_section",
    ),
    path(
        "applications/api/<resource_id>/editor/one-to-many-section/<fk_table_name>/",
        views.ApplicationOneToManyFieldPopupSectionView.as_view(),
        name="application_one_to_many_field_popup_section",
    ),
    path(
        "applications/api/<resource_id>/editor/one-to-one-section/non-dialog-based/<fk_column_name>/",
        views.ApplicationNonDialogBasedOneToOneFieldSectionView.as_view(),
        name="application_editor_non_dialog_based_one_to_one_section",
    ),
    path(
        "applications/api/<resource_id>/editor/one-to-many-section/non-dialog-based/<fk_table_name>/",
        views.ApplicationNonDialogBasedOneToManyFieldSectionView.as_view(),
        name="application_editor_non_dialog_based_one_to_many_section",
    ),
    path(
        "applications/<resource_id>/one-to-one-field/<fk_column_name>/new/",
        views.ApplicationNewOneToOneForeignKeyResourceEditorView.as_view(),
        name="application_new_one_to_one_foreign_key_resource_editor",
    ),
    path(
        "applications/<resource_id>/one-to-one-field/<fk_column_name>/<fk_resource_id>/edit/",
        views.ApplicationOneToOneForeignKeyResourceEditorView.as_view(),
        name="application_one_to_one_foreign_key_resource_update_editor",
    ),
    path(
        "applications/<resource_id>/one-to-many-field/<fk_table_name>/new/",
        views.ApplicationNewOneToManyForeignKeyResourceEditorView.as_view(),
        name="application_new_one_to_many_foreign_key_resource_editor",
    ),
    path(
        "applications/<resource_id>/one-to-many-field/<fk_table_name>/<fk_resource_id>/edit/",
        views.ApplicationOneToManyForeignKeyResourceEditorView.as_view(),
        name="application_one_to_many_foreign_key_resource_update_editor",
    ),
    path(
        "applications/api/<resource_id>/edit/",
        views.ApplicationEditorAutosaveView.as_view(),
        name="application_autosave",
    ),
    path(
        "applications/<resource_id>/overview/",
        views.ApplicationEditorOverviewTemplateView.as_view(),
        name="application_overview",
    ),
    path(
        "applications/<resource_id>/edit/",
        views.ApplicationEditorView.as_view(),
        name="application_editor",
    ),
    path(
        "applications/<resource_id>/delete/",
        views.ApplicationDeletionFormView.as_view(),
        name="delete_application",
    ),
    path(
        "applications/<resource_id>/download/",
        views.ApplicationDescriptionTemplateDownloadView.as_view(),
        name="adt_download",
    ),
]
