from django.urls import path

from . import views
from . import foreign_key_views

app_name = "capacities"

urlpatterns = [
    path(
        "cloud-capacities/",
        views.CloudCapacityListFormView.as_view(),
        name="cloud_capacity_list",
    ),
    path(
        "cloud-capacities/new/",
        views.CloudCapacityEditorStartFormView.as_view(),
        name="new_cloud_capacity",
    ),
    path(
        "cloud-capacities/deletes/",
        views.MultiCloudCapacityDeletionFormView.as_view(),
        name="delete_cloud_capacities",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-one-section/<fk_column_name>/",
        foreign_key_views.CloudCapacityOneToOneFieldEditorSectionView.as_view(),
        name="cloud_capacity_editor_one_to_one_section",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-many-section/<fk_table_name>/",
        foreign_key_views.CloudCapacityOneToManyFieldEditorSectionView.as_view(),
        name="cloud_capacity_editor_one_to_many_section",
    ),
    path(
        "cloud-capacities/api/<resource_id>/edit/",
        views.UpdateCloudCapacityByCategoryView.as_view(),
        name="update_cloud_capacity_by_category",
    ),
    path(
        "cloud-capacities/<resource_id>/overview/",
        views.CloudCapacityEditorOverviewTemplateView.as_view(),
        name="cloud_capacity_overview",
    ),
    path(
        "cloud-capacities/<resource_id>/edit/",
        views.CloudCapacityEditorView.as_view(),
        name="cloud_capacity_editor",
    ),
    path(
        "cloud-capacities/<resource_id>/delete/",
        views.CloudCapacityDeletionFormView.as_view(),
        name="delete_cloud_capacity",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-one-column/<fk_column_name>/new/",
        foreign_key_views.CloudCapacityNewOneToOneRelationFormView.as_view(),
        name="new_cloud_capacity_one_to_one_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-one-column/<fk_column_name>/",
        foreign_key_views.CloudCapacityUpdateOneToOneRelationFormView.as_view(),
        name="update_cloud_capacity_one_to_one_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-one-column/<fk_column_name>/delete/",
        foreign_key_views.CloudCapacityDeleteOneToOneRelationFormView.as_view(),
        name="delete_cloud_capacity_one_to_one_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-many-column/<fk_table_name>/new/",
        foreign_key_views.CloudCapacityNewOneToManyRelationFormView.as_view(),
        name="new_cloud_capacity_one_to_many_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-many-column/<fk_table_name>/<fk_resource_id>/",
        foreign_key_views.CloudCapacityUpdateOneToManyRelationFormView.as_view(),
        name="update_cloud_capacity_one_to_many_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-many-column/<fk_table_name>/<fk_resource_id>/delete/",
        foreign_key_views.CloudCapacityDeleteOneToManyRelationFormView.as_view(),
        name="delete_cloud_capacity_one_to_many_relation",
    ),
    path(
        "cloud-capacities/<resource_id>/download/",
        views.CloudCapacityDescriptionTemplateDownloadView.as_view(),
        name="cloud_cdt_download",
    ),
    path(
        "edge-capacities/",
        views.EdgeCapacityListFormView.as_view(),
        name="edge_capacity_list",
    ),
    path(
        "edge-capacities/new/",
        views.EdgeCapacityEditorStartFormView.as_view(),
        name="new_edge_capacity",
    ),
    path(
        "edge-capacities/deletes/",
        views.MultiEdgeCapacityDeletionFormView.as_view(),
        name="delete_edge_capacities",
    ),
    path(
        "edge-capacities/<resource_id>/overview/",
        views.EdgeCapacityEditorOverviewTemplateView.as_view(),
        name="edge_capacity_overview",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-one-section/<fk_column_name>/",
        foreign_key_views.EdgeCapacityOneToOneFieldEditorSectionView.as_view(),
        name="edge_capacity_editor_one_to_one_section",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-many-section/<fk_table_name>/",
        foreign_key_views.EdgeCapacityOneToManyFieldEditorSectionView.as_view(),
        name="edge_capacity_editor_one_to_many_section",
    ),
    path(
        "edge-capacities/api/<resource_id>/edit/",
        views.UpdateEdgeCapacityByCategoryView.as_view(),
        name="update_edge_capacity_by_category",
    ),
    path(
        "edge-capacities/<resource_id>/edit/",
        views.EdgeCapacityEditorView.as_view(),
        name="edge_capacity_editor",
    ),
    path(
        "edge-capacities/<resource_id>/delete/",
        views.EdgeCapacityDeletionFormView.as_view(),
        name="delete_edge_capacity",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-one-column/<fk_column_name>/new/",
        foreign_key_views.CloudCapacityNewOneToOneRelationFormView.as_view(),
        name="new_edge_capacity_one_to_one_relation",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-one-column/<fk_column_name>/",
        foreign_key_views.CloudCapacityUpdateOneToOneRelationFormView.as_view(),
        name="update_edge_capacity_one_to_one_relation",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-one-column/<fk_column_name>/delete/",
        foreign_key_views.CloudCapacityDeleteOneToOneRelationFormView.as_view(),
        name="delete_edge_capacity_one_to_one_relation",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-many-column/<fk_table_name>/new/",
        foreign_key_views.CloudCapacityNewOneToManyRelationFormView.as_view(),
        name="new_edge_capacity_one_to_many_relation",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-many-column/<fk_table_name>/<fk_resource_id>/",
        foreign_key_views.CloudCapacityUpdateOneToManyRelationFormView.as_view(),
        name="update_edge_capacity_one_to_many_relation",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-many-column/<fk_table_name>/<fk_resource_id>/delete/",
        foreign_key_views.CloudCapacityDeleteOneToManyRelationFormView.as_view(),
        name="delete_edge_capacity_one_to_many_relation",
    ),
    path(
        "edge-capacities/<resource_id>/download/",
        views.EdgeCapacityDescriptionTemplateDownloadView.as_view(),
        name="edge_cdt_download",
    ),
]
