from django.urls import path

from . import views
from . import foreign_key_views

app_name = "capacities"

urlpatterns = [
    path(
        "cloud-capacities/",
        views.CloudCapacityListFormView.as_view(),
        name="cloud_capacity_list",
    ),
    path(
        "cloud-capacities/new/",
        views.CloudCapacityEditorStartFormView.as_view(),
        name="new_cloud_capacity",
    ),
    path(
        "cloud-capacities/deletes/",
        views.MultiCloudCapacityDeletionFormView.as_view(),
        name="delete_cloud_capacities",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-one-popup-section/<fk_column_name>/",
        foreign_key_views.CloudCapacityOneToOneFieldPopupSectionView.as_view(),
        name="cloud_capacity_one_to_one_field_popup_section",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-many-popup-section/<fk_table_name>/",
        foreign_key_views.CloudCapacityOneToManyFieldPopupSectionView.as_view(),
        name="cloud_capacity_one_to_many_field_popup_section",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-one-section/<fk_column_name>/",
        foreign_key_views.CloudCapacityOneToOneFieldSectionView.as_view(),
        name="cloud_capacity_editor_one_to_one_section",
    ),
    path(
        "cloud-capacities/api/<resource_id>/editor/one-to-many-section/<fk_table_name>/",
        foreign_key_views.CloudCapacityOneToManyFieldSectionView.as_view(),
        name="cloud_capacity_editor_one_to_many_section",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-one-field/<fk_column_name>/new/",
        foreign_key_views.CloudCapacityNewOneToOneForeignKeyEditorView.as_view(),
        name="cloud_capacity_new_one_to_one_foreign_key_editor",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-one-field/<fk_column_name>/<fk_resource_id>/edit/",
        foreign_key_views.CloudCapacityOneToOneForeignKeyEditorView.as_view(),
        name="cloud_capacity_one_to_one_foreign_key_update_editor",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-many-field/<fk_table_name>/new/",
        foreign_key_views.CloudCapacityNewOneToManyForeignKeyEditorView.as_view(),
        name="cloud_capacity_new_one_to_many_foreign_key_editor",
    ),
    path(
        "cloud-capacities/<resource_id>/one-to-many-field/<fk_table_name>/<fk_resource_id>/edit/",
        foreign_key_views.CloudCapacityOneToManyForeignKeyEditorView.as_view(),
        name="cloud_capacity_one_to_many_foreign_key_update_editor",
    ),
    path(
        "cloud-capacities/api/<resource_id>/edit/",
        views.CloudCapacityEditorAutosaveView.as_view(),
        name="cloud_capacity_autosave",
    ),
    path(
        "cloud-capacities/<resource_id>/overview/",
        views.CloudCapacityEditorOverviewTemplateView.as_view(),
        name="cloud_capacity_overview",
    ),
    path(
        "cloud-capacities/<resource_id>/overview/one-to-one-field/<fk_column_name>/<fk_resource_id>/",
        foreign_key_views.CloudCapacityOneToOneFieldOverviewSubsectionView.as_view(),
        name="cloud_capacity_overview_one_to_one_field",
    ),
    path(
        "cloud-capacities/<resource_id>/overview/one-to-many-field/<fk_table_name>/",
        foreign_key_views.CloudCapacityOneToManyFieldOverviewSubsectionView.as_view(),
        name="cloud_capacity_overview_one_to_many_field",
    ),
    path(
        "cloud-capacities/<resource_id>/edit/",
        views.CloudCapacityEditorView.as_view(),
        name="cloud_capacity_editor",
    ),
    path(
        "cloud-capacities/<resource_id>/delete/",
        views.CloudCapacityDeletionFormView.as_view(),
        name="delete_cloud_capacity",
    ),
    path(
        "cloud-capacities/<resource_id>/download/",
        views.CloudCapacityDescriptionTemplateDownloadView.as_view(),
        name="cloud_cdt_download",
    ),
    path(
        "edge-capacities/",
        views.EdgeCapacityListFormView.as_view(),
        name="edge_capacity_list",
    ),
    path(
        "edge-capacities/new/",
        views.EdgeCapacityEditorStartFormView.as_view(),
        name="new_edge_capacity",
    ),
    path(
        "edge-capacities/deletes/",
        views.MultiEdgeCapacityDeletionFormView.as_view(),
        name="delete_edge_capacities",
    ),
    path(
        "edge-capacities/<resource_id>/overview/",
        views.EdgeCapacityEditorOverviewTemplateView.as_view(),
        name="edge_capacity_overview",
    ),
    path(
        "edge-capacities/<resource_id>/overview/one-to-one-field/<fk_column_name>/<fk_resource_id>/",
        foreign_key_views.EdgeCapacityOneToOneFieldOverviewSubsectionView.as_view(),
        name="edge_capacity_overview_one_to_one_field",
    ),
    path(
        "edge-capacities/<resource_id>/overview/one-to-many-field/<fk_table_name>/",
        foreign_key_views.EdgeCapacityOneToManyFieldOverviewSubsectionView.as_view(),
        name="edge_capacity_overview_one_to_many_field",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-one-popup-section/<fk_column_name>/",
        foreign_key_views.EdgeCapacityOneToOneFieldPopupSectionView.as_view(),
        name="edge_capacity_one_to_one_field_popup_section",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-many-popup-section/<fk_table_name>/",
        foreign_key_views.EdgeCapacityOneToManyFieldPopupSectionView.as_view(),
        name="edge_capacity_one_to_many_field_popup_section",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-one-section/<fk_column_name>/",
        foreign_key_views.EdgeCapacityOneToOneFieldSectionView.as_view(),
        name="edge_capacity_editor_one_to_one_section",
    ),
    path(
        "edge-capacities/api/<resource_id>/editor/one-to-many-section/<fk_table_name>/",
        foreign_key_views.EdgeCapacityOneToManyFieldSectionView.as_view(),
        name="edge_capacity_editor_one_to_many_section",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-one-field/<fk_column_name>/new/",
        foreign_key_views.EdgeCapacityNewOneToOneForeignKeyEditorView.as_view(),
        name="edge_capacity_new_one_to_one_foreign_key_editor",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-one-field/<fk_column_name>/<fk_resource_id>/edit/",
        foreign_key_views.EdgeCapacityOneToOneForeignKeyEditorView.as_view(),
        name="edge_capacity_one_to_one_foreign_key_update_editor",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-many-field/<fk_table_name>/new/",
        foreign_key_views.EdgeCapacityNewOneToManyForeignKeyEditorView.as_view(),
        name="edge_capacity_new_one_to_many_foreign_key_editor",
    ),
    path(
        "edge-capacities/<resource_id>/one-to-many-field/<fk_table_name>/<fk_resource_id>/edit/",
        foreign_key_views.EdgeCapacityOneToManyForeignKeyEditorView.as_view(),
        name="edge_capacity_one_to_many_foreign_key_update_editor",
    ),
    path(
        "edge-capacities/api/<resource_id>/edit/",
        views.EdgeCapacityEditorAutosaveView.as_view(),
        name="edge_capacity_autosave",
    ),
    path(
        "edge-capacities/<resource_id>/edit/",
        views.EdgeCapacityEditorView.as_view(),
        name="edge_capacity_editor",
    ),
    path(
        "edge-capacities/<resource_id>/delete/",
        views.EdgeCapacityDeletionFormView.as_view(),
        name="delete_edge_capacity",
    ),
    path(
        "edge-capacities/<resource_id>/download/",
        views.EdgeCapacityDescriptionTemplateDownloadView.as_view(),
        name="edge_cdt_download",
    ),
]
